---
- name: Nginx | Install epel-release
  become: true
  yum:
    name: epel-release
    state: present
- name: Nginx | Install Nginx
  become: true
  yum:
    name: nginx
    state: present
  notify: Start nginx
  ignore_errors: "{{ ansible_check_mode }}"
- name: Nginx | Create Nginx config
  become: true
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644
  notify: Reload nginx
- name: Lighthouse | Install git
  become: true
  yum:
    name: git
    state: present
- name: Lighthouse | Create dir for Lighthouse
  become: true
  file:
    path: "{{ lighthouse_location_dir }}"
    state: directory
- name: Lighthouse | Copy lighthouse from git
  become: true
  git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Lighthouse | Create lighthouse config
  become: true
  template:
    src: templates/lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: 0644
  notify: Reload nginx
